(() => {
  'use strict';
  const VERSION = '1.2.0', KEY = 'ielts-vocab-v1:', $ = id => document.getElementById(id);
  const el = {
    progressText:$('progressText'), sessionText:$('sessionText'), progressBar:$('progressBar'), activeRangeText:$('activeRangeText'), activeRangeHint:$('activeRangeHint'), chooseListsBtn:$('chooseListsBtn'), listDialog:$('listDialog'), rangeStart:$('rangeStart'), rangeEnd:$('rangeEnd'), rangePreview:$('rangePreview'), applyRangeBtn:$('applyRangeBtn'),
    positionText:$('positionText'), stateBadge:$('stateBadge'), wordText:$('wordText'), answerPanel:$('answerPanel'), posText:$('posText'), meaningText:$('meaningText'), answerNote:$('answerNote'), promptText:$('promptText'), ratings:$('ratings'), nextBtn:$('nextBtn'), pauseBtn:$('pauseBtn'),
    exportBtn:$('exportBtn'), exportDialog:$('exportDialog'), jsonBtn:$('jsonBtn'), csvBtn:$('csvBtn'), folderExportBtn:$('folderExportBtn'), manageBtn:$('manageBtn'), manageDialog:$('manageDialog'), libraryInfo:$('libraryInfo'), importFile:$('importFile'), importRecordsFile:$('importRecordsFile'), importRecordsFolder:$('importRecordsFolder'), importStatus:$('importStatus'), resetBtn:$('resetBtn'),
    answeredStat:$('answeredStat'), masteredStat:$('masteredStat'), familiarStat:$('familiarStat'), weakStat:$('weakStat'), stubbornStat:$('stubbornStat'), updatedText:$('updatedText')
  };
  const label={1:'秒会',2:'熟悉但犹豫',3:'见过但想不起',4:'完全不会'}, delta={1:20,2:9,3:-14,4:-25};
  let words=[], lists=[], name='雅思词汇乱序版', fingerprint='', state, shownAt=Date.now(), answered=false, session=0;
  const parse=(x,f)=>{try{return x?JSON.parse(x):f}catch{return f}};
  const hash=s=>{let h=2166136261;for(let i=0;i<s.length;i++){h^=s.charCodeAt(i);h=Math.imul(h,16777619)}return(h>>>0).toString(36)};
  function entry(x){const word=String(x.word||'').trim(),meaning=String(x.meaning||'').trim().replace(/\r/g,'');if(!word||!meaning)return null;const id=String(x.id||word).trim().toLowerCase().replace(/\s+/g,' '),found=[...meaning.matchAll(/(?:^|\n)\s*((?:n|v|vi|vt|adj|adv|prep|conj|pron|num|art|int|aux)\.)/gi)].map(m=>m[1].toLowerCase());return{id,word,pos:String(x.pos||[...new Set(found)].join(' / ')||'词性待定'),meaning}}
  function stem(w){return w.toLowerCase().replace(/[^a-z]/g,'').replace(/(ization|isation|ational|ically|ation|ition|ments|ment|ness|able|ible|ical|ally|fully|less|ious|ity|ive|ous|ism|ist|ize|ise|ers|ing|ied|ies|ed|ly|es|s)$/,'')}
  function family(a,b){const aa=a.word.toLowerCase().replace(/[^a-z]/g,''),bb=b.word.toLowerCase().replace(/[^a-z]/g,''),as=stem(a.word),bs=stem(b.word);return as.length>3&&bs.length>3&&(as===bs||aa.startsWith(bb)||bb.startsWith(aa))}
  function autoLists(items){const groups=[];let start=0;while(start<items.length){if(items.length-start<=115){groups.push({start,end:items.length-1});break}const target=start+99;let best=target,score=-1e9;for(let end=Math.max(start+84,target-15);end<=Math.min(items.length-2,target+15);end++){let linked=family(items[end],items[end+1]);for(let k=1;k<=3&&!linked;k++)linked=family(items[end-k],items[end+1]);const s=(linked?-1000:0)-Math.abs(end-target);if(s>score){score=s;best=end}}groups.push({start,end:best});start=best+1}return groups.map((g,i)=>({...g,number:i+1,count:g.end-g.start+1,title:`List ${i+1}`}))}
  function makeFromGroups(groups){let start=0;words=[];lists=[];const seen=new Set();groups.forEach((group,i)=>{const kept=[];(group.words||[]).map(entry).filter(Boolean).forEach(x=>{if(!seen.has(x.id)){seen.add(x.id);kept.push(x)}});if(!kept.length)return;words.push(...kept);lists.push({number:lists.length+1,title:group.title||`List ${i+1}`,start,end:start+kept.length-1,count:kept.length});start+=kept.length});}
  function defaultState(){return{schemaVersion:2,vocabularyFingerprint:fingerprint,index:0,activeRange:{start:1,end:1},paused:false,stats:{},history:[],createdAt:new Date().toISOString(),updatedAt:null}}
  const stateKey=()=>`${KEY}study:${fingerprint}`;
  function load(){state=parse(localStorage.getItem(stateKey()),null)||defaultState();if(!state.stats||!Array.isArray(state.history)||state.vocabularyFingerprint!==fingerprint)state=defaultState();state.activeRange=state.activeRange||{start:1,end:1};state.activeRange.start=Math.min(Math.max(+state.activeRange.start||1,1),lists.length);state.activeRange.end=Math.min(Math.max(+state.activeRange.end||state.activeRange.start,state.activeRange.start),lists.length);state.index=Math.min(Math.max(+state.index||0,0),words.length-1);inRange()}
  function save(){state.updatedAt=new Date().toISOString();localStorage.setItem(stateKey(),JSON.stringify(state))}
  function bounds(){return{start:lists[state.activeRange.start-1].start,end:lists[state.activeRange.end-1].end}}
  function inRange(){const b=bounds();if(state.index<b.start||state.index>b.end)state.index=b.start}
  function selected(){const b=bounds();return words.slice(b.start,b.end+1)}
  const current=()=>words[state.index], record=w=>state.stats[w.id]||null;
  function status(r){if(!r)return{label:'新词',className:'new'};if(r.attempts>=3&&r.masteryScore<35)return{label:'顽固词',className:'stubborn'};if(r.attempts>=2&&r.masteryScore>=80)return{label:'熟词',className:'mastered'};if(r.masteryScore<40)return{label:'薄弱词',className:'weak'};return{label:'不稳定',className:'familiar'}}
  function stats(items=words){const ids=new Set(items.map(x=>x.id)),rs=Object.entries(state.stats).filter(([id])=>ids.has(id)).map(([,r])=>r),out={answered:rs.length,mastered:0,familiar:0,weak:0,stubborn:0,total:items.length};rs.forEach(r=>out[status(r).className]++);return out}
  const rangeText=()=>state.activeRange.start===state.activeRange.end?lists[state.activeRange.start-1].title:`${lists[state.activeRange.start-1].title} – ${lists[state.activeRange.end-1].title}`;
  function update(){const chosen=selected(),s=stats(chosen);for(const [id,key]of Object.entries({answeredStat:'answered',masteredStat:'mastered',familiarStat:'familiar',weakStat:'weak',stubbornStat:'stubborn'}))el[id].textContent=s[key].toLocaleString();el.progressBar.style.width=`${chosen.length?s.answered/chosen.length*100:0}%`;el.progressText.textContent=`本范围已筛选 ${s.answered.toLocaleString()} / ${chosen.length.toLocaleString()} 词`;el.sessionText.textContent=`本次 ${session} 词`;el.activeRangeText.textContent=rangeText();el.activeRangeHint.textContent=`共 ${chosen.length} 词 · ${state.activeRange.end-state.activeRange.start+1} 个 List`;el.updatedText.textContent=state.updatedAt?`更新于 ${new Date(state.updatedAt).toLocaleString('zh-CN')}`:'尚无记录'}
  function render(){inRange();const w=current(),s=status(record(w)),g=lists.find(x=>state.index>=x.start&&state.index<=x.end),b=bounds();el.positionText.textContent=`${g.title} · 本范围第 ${state.index-b.start+1} / ${b.end-b.start+1} 词`;el.stateBadge.textContent=s.label;el.stateBadge.className=`state-badge ${s.className}`;el.wordText.textContent=w.word;el.posText.textContent=w.pos;el.meaningText.textContent=w.meaning;el.answerPanel.classList.add('is-hidden');el.ratings.classList.remove('is-hidden');el.nextBtn.classList.add('is-hidden');el.promptText.textContent=state.paused?'已暂停。按 P 或点击“继续”。':'凭第一反应选择，不用纠结。';el.pauseBtn.textContent=state.paused?'继续':'暂停';[...el.ratings.querySelectorAll('button')].forEach(x=>x.disabled=state.paused);answered=false;shownAt=Date.now();update()}
  function apply(old,ev){const r=+ev.rating,ms=Math.max(0,+ev.reactionMs||0),masteryScore=Math.max(0,Math.min(100,(+old.masteryScore||50)+delta[r]));return{...old,attempts:(+old.attempts||0)+1,totalReactionMs:(+old.totalReactionMs||0)+ms,masteryScore,correctStreak:r<=2?(+old.correctStreak||0)+1:0,difficultStreak:r>=3?(+old.difficultStreak||0)+1:0,lastRating:r,lastReactionMs:ms,lastAnsweredAt:ev.answeredAt}}
  function answer(rating){if(answered||state.paused)return;const w=current(),reactionMs=Math.max(0,Date.now()-shownAt),old=record(w)||{word:w.word,pos:w.pos,meaning:w.meaning,attempts:0,totalReactionMs:0,masteryScore:50,correctStreak:0,difficultStreak:0},ev={wordId:w.id,word:w.word,pos:w.pos,meaning:w.meaning,rating,reactionMs,answeredAt:new Date().toISOString()},next=apply(old,ev);state.stats[w.id]=next;state.history.push({...ev,ratingLabel:label[rating],attemptsAfter:next.attempts,masteryScoreAfter:next.masteryScore,statusAfter:status(next).label});answered=true;session++;save();el.answerPanel.classList.remove('is-hidden');el.ratings.classList.add('is-hidden');el.nextBtn.classList.remove('is-hidden');el.answerNote.textContent=`${label[rating]} · 反应 ${(reactionMs/1000).toFixed(1)} 秒 · 当前状态：${status(next).label}`;el.promptText.textContent='看完释义后按 Enter / 空格，继续下一个。';update()}
  function next(){if(!answered||state.paused)return;const b=bounds();state.index=state.index>=b.end?b.start:state.index+1;save();render()}
  function pause(){state.paused=!state.paused;save();if(answered){el.pauseBtn.textContent=state.paused?'继续':'暂停';el.promptText.textContent=state.paused?'已暂停。继续后可进入下一个。':'看完释义后按 Enter / 空格，继续下一个。';return}if(!state.paused)shownAt=Date.now();render()}
  function fillRange(){[el.rangeStart,el.rangeEnd].forEach(s=>{s.textContent='';lists.forEach(g=>{const o=document.createElement('option');o.value=g.number;o.textContent=`${g.title} · ${g.count} 词`;s.append(o)})});el.rangeStart.value=state.activeRange.start;el.rangeEnd.value=state.activeRange.end;previewRange()}
  function previewRange(){const start=+el.rangeStart.value,end=Math.max(start,+el.rangeEnd.value);el.rangeEnd.value=end;const count=lists.slice(start-1,end).reduce((n,g)=>n+g.count,0);el.rangePreview.textContent=`将学习 ${lists[start-1].title}${start===end?'':` – ${lists[end-1].title}`}：共 ${count} 词，${end-start+1} 个 List。`}
  function setRange(){state.activeRange={start:+el.rangeStart.value,end:+el.rangeEnd.value};state.index=lists[state.activeRange.start-1].start;state.paused=false;save();el.listDialog.close();render()}
  const escape=v=>/[",\n\r]/.test(String(v??''))?`"${String(v).replaceAll('"','""')}"`:String(v??'');
  function csv(){const head=['word','part_of_speech','chinese_meaning','rating','rating_label','reaction_ms','answered_at','attempts_after','mastery_score_after','status_after'];return'\uFEFF'+[head.join(','),...state.history.map(x=>[x.word,x.pos,x.meaning,x.rating,x.ratingLabel,x.reactionMs,x.answeredAt,x.attemptsAfter,x.masteryScoreAfter,x.statusAfter].map(escape).join(','))].join('\r\n')}
  function json(){return JSON.stringify({schemaVersion:2,exportedAt:new Date().toISOString(),appVersion:VERSION,vocabulary:{name,totalWords:words.length,fingerprint,lists:lists.map(g=>({number:g.number,title:g.title,count:g.count}))},activeRange:state.activeRange,summary:stats(),wordRecords:state.stats,answerHistory:state.history},null,2)}
  function date(){return new Date().toISOString().slice(0,10)}
  function download(file,data,type){const u=URL.createObjectURL(new Blob([data],{type})),a=document.createElement('a');a.href=u;a.download=file;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
  function expJson(){download(`词汇学习记录_${date()}.json`,json(),'application/json;charset=utf-8');el.exportDialog.close()}
  function expCsv(){download(`词汇学习明细_${date()}.csv`,csv(),'text/csv;charset=utf-8');el.exportDialog.close()}
  async function expFolder(){const j=`词汇学习记录_${date()}.json`,c=`词汇学习明细_${date()}.csv`;try{if(!window.showDirectoryPicker)throw Error('unsupported');const d=await window.showDirectoryPicker({mode:'readwrite'});for(const [file,data]of [[j,json()],[c,csv()]]){const h=await d.getFileHandle(file,{create:true}),w=await h.createWritable();await w.write(data);await w.close()}el.exportDialog.close();alert(`已保存到所选文件夹：\n${j}\n${c}`)}catch(e){if(e.name==='AbortError')return;download(j,json(),'application/json;charset=utf-8');download(c,csv(),'text/csv;charset=utf-8');alert('当前浏览器不支持选择保存文件夹，已改为下载两份文件。')}}
  function lines(text){return text.replace(/^\uFEFF/,'').split(/\r?\n/)}
  function parseListFile(text){const groups=[],seen=new Set();let group=null;for(const raw of lines(text)){const line=raw.trim();if(!line||line.startsWith('//'))continue;const heading=line.match(/^#{1,6}\s*(?:list\s*)?(\d+)(?:\s*[:：-]\s*(.*))?$/i);if(heading){group={title:heading[2]?`List ${heading[1]} · ${heading[2]}`:`List ${heading[1]}`,words:[]};groups.push(group);continue}if(line.startsWith('#'))continue;if(!group)continue;let part=raw.split('\t');if(part.length<2)part=raw.split(/\s*,\s*/,3);if(part.length<2)continue;const x=entry({word:part[0],pos:part.length>2?part[1]:'',meaning:part.length>2?part.slice(2).join('\t'):part[1]});if(x&&!seen.has(x.id)){seen.add(x.id);group.words.push(x)}}return groups.filter(g=>g.words.length)}
  async function importVocab(file){const groups=parseListFile(await file.text());if(!groups.length){alert('没有识别到 List。自定义词库必须用“## List 1”作为每组标题，并在标题下用 Tab 分隔：英文、词性、中文释义。可先打开“词库格式模板.txt”。');return}const count=groups.reduce((n,g)=>n+g.words.length,0);if(!confirm(`识别到 ${groups.length} 个 List、${count} 个去重词条。导入后将使用新词库，是否继续？`))return;localStorage.setItem(`${KEY}customLibrary`,JSON.stringify({name:file.name.replace(/\.[^.]+$/,''),groups}));location.reload()}
  function csvRows(t){const out=[];let row=[],field='',q=false;for(let i=0;i<t.length;i++){const c=t[i],n=t[i+1];if(c==='"'){if(q&&n==='"'){field+='"';i++}else q=!q}else if(c===','&&!q){row.push(field);field=''}else if((c==='\n'||c==='\r')&&!q){if(c==='\r'&&n==='\n')i++;row.push(field);if(row.some(x=>x.trim()))out.push(row);row=[];field=''}else field+=c}row.push(field);if(row.some(x=>x.trim()))out.push(row);return out}
  const byId=x=>{const id=String(x||'').trim().toLowerCase();return words.find(w=>w.id===id||w.word.toLowerCase()===id)};
  function event(raw){const w=byId(raw.wordId||raw.word),r=+(raw.rating||0),d=new Date(raw.answeredAt||raw.answered_at);if(!w||![1,2,3,4].includes(r)||Number.isNaN(d))return null;return{wordId:w.id,word:w.word,pos:w.pos,meaning:w.meaning,rating:r,ratingLabel:label[r],reactionMs:Math.max(0,+((raw.reactionMs??raw.reaction_ms)||0)),answeredAt:d.toISOString()}}
  function rebuild(){state.history.sort((a,b)=>new Date(a.answeredAt)-new Date(b.answeredAt));state.stats={};state.history=state.history.map(e=>{const w=byId(e.wordId),old=state.stats[w.id]||{word:w.word,pos:w.pos,meaning:w.meaning,attempts:0,totalReactionMs:0,masteryScore:50,correctStreak:0,difficultStreak:0},n=apply(old,e);state.stats[w.id]=n;return{...e,attemptsAfter:n.attempts,masteryScoreAfter:n.masteryScore,statusAfter:status(n).label}})}
  async function importRecords(files){const incoming=[];for(const f of [...files])try{const text=await f.text();if(/\.json$/i.test(f.name)){const x=JSON.parse(text);(x.answerHistory||x.history||[]).forEach(r=>{const e=event(r);if(e)incoming.push(e)})}else if(/\.csv$/i.test(f.name)){const r=csvRows(text.replace(/^\uFEFF/,'')),h=(r.shift()||[]).map(x=>x.toLowerCase());r.forEach(row=>{const o={};h.forEach((k,i)=>o[k]=row[i]);const e=event(o);if(e)incoming.push(e)})}}catch{}const key=e=>`${e.wordId}|${e.answeredAt}|${e.rating}|${e.reactionMs}`,known=new Set(state.history.map(key)),add=incoming.filter(e=>!known.has(key(e)));add.forEach(e=>known.add(key(e)));if(!add.length){el.importStatus.textContent=incoming.length?'没有新增记录（可能已导入）。':'未识别到能导入的记录。';return}state.history.push(...add);rebuild();save();el.importStatus.textContent=`已合并 ${add.length} 条记录；当前共 ${state.history.length} 条。`;render()}
  function reset(){if(!confirm('确定清空当前词库的全部学习记录吗？请先导出 JSON 备份。'))return;localStorage.removeItem(stateKey());session=0;load();render();el.manageDialog.close()}
  function init(){const custom=parse(localStorage.getItem(`${KEY}customLibrary`),null);if(Array.isArray(custom?.groups)){name=custom.name;makeFromGroups(custom.groups)}else{const seen=new Set();words=(window.VOCABULARY||[]).map(entry).filter(x=>x&&!seen.has(x.id)&&seen.add(x.id));lists=autoLists(words)}fingerprint=hash(words.map(x=>`${x.id}|${x.meaning}`).join('\n')+'|'+lists.map(x=>x.start).join(','));load();fillRange();el.libraryInfo.textContent=`当前词库：${name} · ${words.length.toLocaleString()} 个词条 · ${lists.length} 个 List。`;render()}
  el.ratings.addEventListener('click',e=>{const b=e.target.closest('[data-rating]');if(b)answer(+b.dataset.rating)});el.nextBtn.onclick=next;el.pauseBtn.onclick=pause;el.chooseListsBtn.onclick=()=>{fillRange();el.listDialog.showModal()};el.rangeStart.onchange=previewRange;el.rangeEnd.onchange=previewRange;el.applyRangeBtn.onclick=setRange;
  el.exportBtn.onclick=()=>el.exportDialog.showModal();el.jsonBtn.onclick=expJson;el.csvBtn.onclick=expCsv;el.folderExportBtn.onclick=expFolder;el.manageBtn.onclick=()=>el.manageDialog.showModal();el.importFile.onchange=e=>e.target.files[0]&&importVocab(e.target.files[0]);el.importRecordsFile.onchange=e=>importRecords(e.target.files);el.importRecordsFolder.onchange=e=>importRecords(e.target.files);el.resetBtn.onclick=reset;document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>$(b.dataset.close).close());
  document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if(e.key.toLowerCase()==='p'){e.preventDefault();pause()}else if(/^[1-4]$/.test(e.key)){e.preventDefault();answer(+e.key)}else if((e.key==='Enter'||e.key===' ')&&answered){e.preventDefault();next()}});init();
})();
